window.content = [
/*     {id: 1, 
        img: "", 
        mainPic: "",
        title: "", 
        content: '', 
        title2: '', 
        content2: '', 
        title3: '', 
        content3: '', 
        title4:'',
        content4:'',
        title5:'',
        content5:'',
        title6:'',
        content6:'',
        title7:'',
        content7:'',
        title8:'',
        content8:'',
        title9:'',
        content9:'',
        title10:'',
        content10:'',
    
        date: '4 - 9 - 2024', 
        author: 'by James Kwong',
        youtubeLink:' ',
    
        adsIntro:'',
        adslink:'',
        adsIntro2:'',
        adslink2:'',
        adsIntro3:'',
        adslink3:'',
    
    }, */
    
    {id: 1, 
     img: "img/img-01.png", 
    mainPic: "img/img-01.png",
    title: 'Learn about passive income now and take the first step to becoming a slash youth!', 
    content: 'How to create passive income?\nTeach you to make good use of your interests to build stable passive income', 
    title2: 'Passive income & petty bourgeoisie entrepreneurship recommendation--turn interest into income through "hobby entrepreneurship"', 
    content2: 'How can office workers increase their income? Instead of looking for part-time jobs in different channels, such as delivering food, driving multiple taxis and other highly substitutable one-time service methods, it is better to find a model that can bring continuous income. Only then will there be a cumulative effect, and the more you do it, the easier it will be, especially in modern business models. With the rapid development of technology, the opportunities for creating passive income through the Internet are becoming more diverse and the threshold is not high. Hobby entrepreneurship is a popular entrepreneurial trend in the Internet era. Starting from your own interests and hobbies, you can form interest communities on social media such as FB and IG to cultivate fans and interact with each other. When others recognize you, you will naturally be influential. , attracting more new friends. When you expand your circle of friends, it will be easier to contact customers, develop new customer groups, and have more opportunities to monetize your interests..', 
    title3: 'How to start a business if you are interested? Here are some success stories!', 
    content3: 'Entrepreneurship direction is unclear?  Food, cooking, coffee, yoga, fitness, beauty, etc. in life are all themes of hobby entrepreneurship. Take a look at the successful entrepreneurial cases of two Amway direct sellers. You can also play with your hobbies and successfully start a business like them!(1) Su Hongling, who has crossed over from the catering industry, chose to start a business from what women care most about: "becoming beautiful". She first spent a year and a half studying and studying online makeup teaching, improving "self-transformation", and doing makeup before and after As soon as the photos were posted online, they sparked heated discussions and greatly boosted his confidence. He then went on to engage in "amateur transformation" online, IG live broadcast makeup tutorials, and new product unboxing videos. She also connected offline physical activities and services to provide product experience. Share your experience, teach face-to-face beauty and skin care techniques, and accompany customers to solve skin problems, and also create good sales results for yourself.(2) Ke Youjing, who has diverse interests, has established three major communities: food, beauty and beauty. Through self-media, she posts every day, with topics ranging from beauty tips to snack teaching. She shares her favorite things to create topics, which will also influence The force spreads out. For example, the "10-minute fitness at home" video was shared to the home exercise community. Because the content is simple and easy to implement, and everyone encourages each other, not only the interactive performance is super good, but the fan attraction has also achieved breakthrough growth. Online friend circles created based on interests, combined with offline pleasant interactive experiences, make the community more closely connected, not only attracting a group of like-minded partners, but also creating unlimited business opportunities..', 
    date: '4 - 9 - 2024', 
    author: 'by James Kwong',
    youtubeLink:'',
    adslink:'https://amzn.to/3zfsG2y',

    },
   
//Slashie

    {id: 2, 
    img: "img/img-02.jpg", 
    mainPic: "img/img-02.jpg",
    title: 'How to get rid of the cycle of "work - quit - job search - quit again"', 
    content: 'I’ve gone through this cycle of working, quitting, applying for a job, starting a new job, and quitting again many times. In fact, there is nothing wrong with changing jobs. Your salary can be increased as a result, and the accumulated experience can be applied to larger projects. The problem is that after repeating this cycle several times, you still don’t know what you want to do. It seems that as long as you work in Going in circles, not moving forward.', 
    title2: 'The purpose and meaning of work', 
    content2: 'What is the purpose and meaning of work for you? I think it should be that someone is helped/touched/inspired by your work/works/products, and thus gets a sense of satisfaction. The focus here is on responses and metrics that allow you to measure effectiveness. If you are a teacher, you can know whether your work is effective from the growth and academic performance of your students; if you are a content creator, the opinions and support of readers/viewers are the driving force for creation. There are many ways to help others, it all depends on how you use your expertise. In order to do your job better or solve more difficult problems, you need to overcome difficulties and break through yourself so that you can feel yourself growing and move towards the next stage of learning. Through work, we experience our own value and then get money from it.', 
    title3: 'Does your job equip you and provide you with space to thrive?', 
    content3: 'But going back to 5 or 10 years ago, I had no idea what I wanted to do, so if I could remind myself in Year 4, I would tell her that if she didn’t know what kind of job she wanted to do in the future, go ahead and do it first Work in a big company and get to know different businesses. The years after graduation are key to learning. Learn from great managers and understand the systems they use to ensure the company runs smoothly. It is easy to work in a large company first and then transfer to a small and medium-sized enterprise, but it is much more difficult to move from a small and medium-sized enterprise to a large company. It turns out that the reason why I fell into the cycle of "working - quitting - applying for a job - quitting again" was because I lacked life goals and long-term planning. I didnt plan what I wanted to get from that company, but passively accepted the opportunities provided there. I felt that there was no Left after other new experiences. Now that I think about it, a better approach would be to set phased goals for your career development. If you dont have this opportunity, you have to create it yourself. What do you want to be in five years? How do you prepare? Does your job equip you and provide you with space to thrive? ', 
    date: '4 - 9 - 2024', 
    author: 'by James Kwong',
    youtubeLink:' ',
    adslink:'https://amzn.to/3zfsG2y',


},
    
    {id: 3, 
    img: "img/img-03.jpg", 
    mainPic: "img/img-03.jpg",
    title: 'Slasher pros and cons', 
    content: 'Being a Slasher is equivalent to being your own boss. You can enjoy flexible working hours and locations. You can choose a variety of jobs and earn more than a full-time job. There are many types of Slasher jobs that only require a computer to handle official work. They are not restricted by location or time, and you can also work while traveling.', 
    title2: 'Slasher Benefits', 
    content2: 'Being a Slasher is equivalent to being your own boss. You can enjoy flexible working hours and locations. You can choose a variety of jobs and earn more than a full-time job. There are many types of Slasher jobs that only require a computer to handle official work. They are not restricted by location or time, and you can also work while traveling. In an era of rapid changes in the business world, Slashers have multiple skills and incomes at the same time, which can broaden their horizons and abilities in career development, and become more secure than traditional jobs. For example, during the epidemic, if the income of one of the jobs is greatly reduced or even laid off, at least there will be income from other jobs to make up for it.', 
    title3: 'Slasher Disadvantages', 
    content3: 'Being a slasher is like starting a one-person company. You are responsible for all business search, online and offline promotion, paperwork, contract processing, design, accounting, and even remuneration collection. Moreover, the labor is unstable and there are no specific working hours. Many times I have to work on Saturdays and Sundays. Since Slasher has no specific working hours, most clients expect to be able to find you anytime, anywhere. When the workload is too much and you juggle several jobs at the same time, the mental pressure you face may be greater than working full-time. When the workload is too little and financial constraints are at the same time, it may not be possible to choose only jobs that interest you. Especially in the early days of becoming a slasher, the time and effort you put in may not be directly proportional to your income. Therefore, it is very important to find a career that "will make you enjoy yourself even if you have no money to earn." If you want to enjoy the benefits of being a slasher, you must be self-disciplined, have a sense of time, and work hard to build your personal brand and reputation..', 
    date: '4 - 9 - 2024', 
    author: 'by James Kwong',
    youtubeLink:' ',
    adslink:'https://amzn.to/3zfsG2y',


},

{id: 4, 
    img: "img/img-04.jpg", 
    mainPic: "img/img-04.jpg",
    title: "How to become a Slasher", 
    content: 'Before joining as a slasher, you need to prepare a portfolio, help promote yourself, understand the market situation, competitors trends, lock in customer groups and reserve customers.', 
    title2: 'Success Slasher', 
    content2: 'Before joining as a slasher, you need to prepare a portfolio, help promote yourself, understand the market situation, competitors trends, lock in customer groups and reserve customers. Many slashers will put their portfolios on Instagram, Facebook and Blog to promote their personal brands and services. In the early stages of becoming a slasher, people may not buy your services right away. In the early stages of starting a business, you may need to provide services for free, build a reputation, hope to get recommendations from customers, and finally earn income. You need to be adventurous and dont be afraid of bottoming out.', 
    title3: 'How should Slashers protect themselves?', 
    content3: 'Being a Slasher requires good communication skills, time management, and the ability to manage reasonable customer expectations. In order to protect the rights and interests of both parties, Slasher needs to clarify the terms and conditions of cooperation before cooperating with the employer, and list them on the documents and contracts. For example, the balance of the remuneration needs to be paid within 7-14 days from the day the service is completed to protect your rights and cash flow. There are websites on the market that provide free document examples for you to design and download your own version of the document.At the same time, the slasher should retain all email conversations and transaction documents with customers. In addition, customers can also be required to pay a 30% to 50% deposit before providing services. Beyond that, managing customer expectations is important. Slasher If you dont know how to set a bottom line, flexible working hours will become a 24-hour work schedule..', 
    date: '4 - 9 - 2024', 
    author: 'by James Kwong',
    youtubeLink:' ',
    adslink:'https://amzn.to/3zfsG2y',


},

/* {id: 5, 
    img: "img/img-04.jpg", 
    mainPic: "img/img-04.jpg",
    title: "How to become a Slasher", 
    content: 'Before joining as a slasher, you need to prepare a portfolio, help promote yourself, understand the market situation, competitors trends, lock in customer groups and reserve customers.', 
    title2: 'Success Slasher', 
    content2: 'Before joining as a slasher, you need to prepare a portfolio, help promote yourself, understand the market situation, competitors trends, lock in customer groups and reserve customers. Many slashers will put their portfolios on Instagram, Facebook and Blog to promote their personal brands and services. In the early stages of becoming a slasher, people may not buy your services right away. In the early stages of starting a business, you may need to provide services for free, build a reputation, hope to get recommendations from customers, and finally earn income. You need to be adventurous and dont be afraid of bottoming out.', 
    title3: 'How should Slashers protect themselves?', 
    content3: 'Being a Slasher requires good communication skills, time management, and the ability to manage reasonable customer expectations. In order to protect the rights and interests of both parties, Slasher needs to clarify the terms and conditions of cooperation before cooperating with the employer, and list them on the documents and contracts. For example, the balance of the remuneration needs to be paid within 7-14 days from the day the service is completed to protect your rights and cash flow. There are websites on the market that provide free document examples for you to design and download your own version of the document.At the same time, the slasher should retain all email conversations and transaction documents with customers. In addition, customers can also be required to pay a 30% to 50% deposit before providing services. Beyond that, managing customer expectations is important. Slasher If you dont know how to set a bottom line, flexible working hours will become a 24-hour work schedule..', 
    title4:'4',
    content4:'4',
    title5:'5',
    content5:'5',
    title6:'6',
    content6:'6',
    title7:'7',
    content7:'7',
    title8:'8',
    content8:'8',
    title9:'9',
    content9:'9',
    title10:'10',
    content10:'10',

    date: '4 - 9 - 2024', 
    author: 'by James Kwong',
    youtubeLink:' ',

    adsIntro:'11123123123123',
    adslink:'https://amzn.to/3zfsG2y',
    adsIntro2:'22',
    adslink2:'https://amzn.to/3zfsG2y',
    adsIntro3:'33',
    adslink3:'https://amzn.to/3zfsG2y',

},
 */




];